### PR TITLE
Rethreading and Merge Hash Change handling

### PR DESCRIPTION
**Pull request by TheV360**
uhhhh can someone test this for me

### CODE REVIEW

**Comment by TheV360** [comment]
Demo here:

https://github.com/user-attachments/assets/86d91c93-0c4a-4405-a148-b724e678076c

This is using [a separate script](https://github.com/TheV360/qcs-frontend-sbs2/blob/6d780dea23684ce8f2ebdc1f875e23fd7803d011/src/messages.js#L516-L592) to poke at messages' values (specifically nickname, here) to change the merge hash of a comment.

**Comment by darienreese** [comment]
I'll look at this in a bit

**Comment by darienreese** [comment]
Rethreading messages that arrive before some content creates an error "unimplemented: rethread"
image
image
The messages leaving the chat seem to work, and messages that get appended at the end also work

**Comment by TheV360** [comment]
aah hell. ok. facing some difficulties with this thus far. working on a good testing environment for this. came up with something cute on a walk today

**Comment by TheV360** [comment]
test script (not the thing i thought was fun, but is still fun itself) made..

<details><summary><code>lazy_river.py</code></summary>

```python
#! /usr/bin/python
import time
from random import randrange
from typing import List
import requests

class Capi:
	SITE: str = r"http://localhost:5147/api"
	
	token: str
	
	def get_headers(self) -> dict:
		return {
			'Authorization': f"Bearer {self.token}",
		}
	
	def __init__(self, token: str):
		self.token = token
	
	@staticmethod
	def login(username, password) -> 'Capi':
		return Capi(requests.post(
			Capi.SITE + r"/user/login",
			None, {
				'username': username,
				'password': password,
			}
		).text)
	
	def get_message_ids_of(self, room_id, to_fetch = 5) -> list[int]:
		return [
			message['id']
			for message in
			requests.post(
				Capi.SITE + r"/request",
				None, {
					'values': { 'pid': room_id, },
					'requests': [
						{
							'type': 'message',
							'fields': 'id,contentId',
							'query': 'contentId = @pid and !notdeleted()',
							'order': 'id_desc',
							'limit': to_fetch,
							'skip': 0,
						},
					],
				},
				headers=self.get_headers()
			).json()['objects']['message']
		]
	
	def rethread(
		self,
		target_room_id: int,
		message_ids: List[int],
		gravestone: str = "blah"
	):
		return requests.post(
			Capi.SITE + r"/shortcuts/rethread",
			None, {
				'messageIds': message_ids,
				'contentId': target_room_id,
				'message': gravestone,
			},
			headers=self.get_headers()
		)

creds = ('braixen', 'plaintextpassword')
room_ids = [ 7, 8, 9 ]
capi = Capi.login(*creds)

first_room_index = 1
first_room = room_ids[first_room_index]

message_ids = capi.get_message_ids_of(first_room)
message_ids.sort()

recent_room_index = first_room_index

try:
	while True:
		next_room_index = randrange(len(room_ids) - 1)
		if next_room_index >= recent_room_index:
			next_room_index += 1
		
		recent_room = room_ids[recent_room_index]
		next_room = room_ids[next_room_index]
		
		print(f"moving messages from {recent_room} to {next_room}")
		
		print(capi.rethread(next_room, message_ids))
		recent_room_index = next_room_index
		
		time.sleep(1)
except KeyboardInterrupt:
	print("heck, please!")
	
	time.sleep(1)
	
	print(f"putting messages back into {first_room}")
	capi.rethread(first_room, message_ids)
	
	time.sleep(1)
	
	print("alright, how's that...")

```

</details>

in action:

https://github.com/user-attachments/assets/d52c37d0-1618-4647-828d-8484329e2d6b

**Comment by TheV360** [comment]
In action:

https://github.com/user-attachments/assets/878bdf89-6a38-43fa-974e-05056ab3b630

**Pull request merged**
